on: [push, pull_request]

name: PyPi packaging

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: ubuntu 
            os: ubuntu-latest
            arch: x86-64

          - name: macos
            os: macos-latest
            arch: x86-64

          - name: macos-arm64
            os: macos-latest
            arch: arm64

    runs-on: ${{ matrix.os }}
    if: (github.repository == 'cvc5/cvc5') || (github.event_name != 'schedule')

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      if: runner.os == 'Linux'
      with:
        with-documentation: false
        with-python-bindings: false
        with-python-packaging: true

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      if: runner.os == 'macOS'
      with:
        with-documentation: false
        with-python-bindings: true
        with-python-packaging: true

    - name: Setup caches
      uses: ./.github/actions/setup-cache
      with:
        cache-key: cvc5-pypi

    - name: Package PyPi wheel packages
      uses: ./.github/actions/package-python-wheel
      with:
        arch: ${{ matrix.arch }}
        upload-to-pypi: ${{ github.event_name == 'release' }}
        upload-to-test-pypi: false
        test-pypi-token: ${{ secrets.PYPI_TOKEN }}
        pypi-token: ${{ secrets.PYPI_TOKEN }}

    - name: Upload wheel artifact
      uses: actions/upload-artifact@v2
      with:
        path: '*.whl'
